## constants ##

# categories and accounts
MORATORIAS = "MORATORIAS"
MORATORIA_AFIP = "MORATORIA AFIP"
IMPUESTOS = "Impuestos"
NEW_CATEGORY = "*** NUEVO RUBRO ***"
CARGAS_SOCIALES = "CARGAS SOCIALES"
SUELDOS = "SUELDOS"
ANNULED = "ANULADO"
PRESTAMOS_BANCARIOS = "Préstamos bancarios"

# transfers
T_E_CUENTAS_PROPIAS = "T/E CUENTAS PROPIAS"

# flows
ACTUAL_FLOW = 'Actual'
ESTIMATED_FLOW = 'Proyectado'
FLEXIBLE = "Negociable"
INFLEXIBLE = "Impostergable"

# flow types
CAJAS_TYPE = 'Caja'
CHEQUES_TYPE = 'Cheques terceros'
CREDICOOP_TYPE = 'Banco Credicoop'

# sheets

RUBROS_SHEET_NAME = 'Rubros'
CHEQUES_SHEET_NAME = 'CHQ TERCEROS'
CAJA_SHEET_NAME = 'CAJA'
CREDICOOP_SHEET_NAME = 'CREDICOOP'
CUENTAS_CORRIENTES_SHEET_NAME = 'CTA CTES'

# banks with credits
BANKS = ['FELSIM COMAFI', 'FELSIM NACIÓN', 'FELSIM BAPRO']
